# **Aula Interativa 1**

---

Métricas de Desempenho

### *Importando* bibliotecas


In [ ]:
import pandas as pd #biblioteca para manipulação de dados
import numpy as np #biblioteca para utilizacao de vetores e matrizes
import matplotlib.pyplot as plt #bibloteca para plotar graficos

In [ ]:
#liberando acesso do colab aos arquivos no drive
# from google.colab import drive
# drive.mount('/content/gdrive')

from google.colab import files

In [ ]:
uploaded_r = files.upload()

Saving bike_day.csv to bike_day.csv


In [ ]:
uploaded_cf = files.upload()

Saving australian.csv to australian.csv


In [ ]:
uploaded_cs = files.upload()

Saving vehicle.csv to vehicle.csv


### Carregamento dos dados

In [ ]:
#lendo o csv que contem as base de dados em dfs
#https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset
# df_r = pd.read_csv('/content/gdrive/My Drive/IGTI/AulaInterativa1/bike_day.csv')
df_r = pd.read_csv('bike_day.csv')

#https://www.openml.org/d/40981
# df_cf = pd.read_csv('/content/gdrive/My Drive/IGTI/AulaInterativa1/australian.csv')
df_cf = pd.read_csv('australian.csv')

#https://www.openml.org/d/54
# df_cs = pd.read_csv('/content/gdrive/My Drive/IGTI/AulaInterativa1/vehicle.csv')
df_cs = pd.read_csv('vehicle.csv')

In [ ]:
#imprimindo as 5 primeiras linhas do df para confirmação
df_r.head(5)

instant      dteday  season  yr  ...  windspeed  casual  registered   cnt
0        1  2011-01-01       1   0  ...   0.160446     331         654   985
1        2  2011-01-02       1   0  ...   0.248539     131         670   801
2        3  2011-01-03       1   0  ...   0.248309     120        1229  1349
3        4  2011-01-04       1   0  ...   0.160296     108        1454  1562
4        5  2011-01-05       1   0  ...   0.186900      82        1518  1600

[5 rows x 16 columns]

In [ ]:
df_r = df_r.drop(['instant', 'dteday'], axis=1)
df_r.head()

season  yr  mnth  holiday  ...  windspeed  casual  registered   cnt
0       1   0     1        0  ...   0.160446     331         654   985
1       1   0     1        0  ...   0.248539     131         670   801
2       1   0     1        0  ...   0.248309     120        1229  1349
3       1   0     1        0  ...   0.160296     108        1454  1562
4       1   0     1        0  ...   0.186900      82        1518  1600

[5 rows x 14 columns]

In [ ]:
df_cf.head(5)

A1   A2   A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15
0   1   65  168   2   4   4  39   0   0    1    1    2   32  161    0
1   0   72  123   2   8   4   5   0   0    1    0    2   53    1    0
2   0  142   52   1   4   4  31   0   0    1    1    2   98    1    0
3   0   60  169   1   5   3   1   1   1   12    1    2    1    1    1
4   1   44  134   2   6   4  46   1   1   15    0    2   18   68    1

In [ ]:
df_cs.head(5)

COMPACTNESS  CIRCULARITY  ...  HOLLOWS_RATIO  Class
0           95           48  ...            197    van
1           91           41  ...            199    van
2          104           50  ...            196   saab
3           93           41  ...            207    van
4           85           44  ...            183    bus

[5 rows x 19 columns]

In [ ]:
# Verificando o numero de amostras (linhas) e features (colunas) do dataset. 
print('Amostras e Features:', df_r.shape)
print('Amostras e Features:', df_cf.shape)
print('Amostras e Features:', df_cs.shape)

Amostras e Features: (731, 14)
Amostras e Features: (690, 15)
Amostras e Features: (846, 19)


In [ ]:
# Verificando quais são os tipos das features
df_r.columns

Index(['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt'],
      dtype='object')

In [ ]:
df_cf.columns

Index(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11',
       'A12', 'A13', 'A14', 'A15'],
      dtype='object')

In [ ]:
df_cs.columns

Index(['COMPACTNESS', 'CIRCULARITY', 'DISTANCE_CIRCULARITY', 'RADIUS_RATIO',
       'PR.AXIS_ASPECT_RATIO', 'MAX.LENGTH_ASPECT_RATIO', 'SCATTER_RATIO',
       'ELONGATEDNESS', 'PR.AXIS_RECTANGULARITY', 'MAX.LENGTH_RECTANGULARITY',
       'SCALED_VARIANCE_MAJOR', 'SCALED_VARIANCE_MINOR',
       'SCALED_RADIUS_OF_GYRATION', 'SKEWNESS_ABOUT_MAJOR',
       'SKEWNESS_ABOUT_MINOR', 'KURTOSIS_ABOUT_MAJOR', 'KURTOSIS_ABOUT_MINOR',
       'HOLLOWS_RATIO', 'Class'],
      dtype='object')

### Pré processamento

In [ ]:
print(np.unique(df_cf['A15']))
print(np.unique(df_cs['Class']))

[0 1]
['bus' 'opel' 'saab' 'van']


Mapeamentos das classes

In [ ]:
#criando um dicionario de dados para o mapeamento
name_to_class = {
    'bus': 0,
    'opel': 1,
    'saab': 2,
    'van': 3
}

#substituindo os valores categóricos pelo mapeamento
df_cs['Class'] = df_cs['Class'].map(name_to_class)

#check
df_cs.head(5)

COMPACTNESS  CIRCULARITY  ...  HOLLOWS_RATIO  Class
0           95           48  ...            197      3
1           91           41  ...            199      3
2          104           50  ...            196      2
3           93           41  ...            207      3
4           85           44  ...            183      0

[5 rows x 19 columns]

Uma outra etapa importante do pré-processamento consiste na avaliação de dados faltantes. 



In [ ]:
# Analisando o resumo da base
df_r.describe()

season          yr  ...   registered          cnt
count  731.000000  731.000000  ...   731.000000   731.000000
mean     2.496580    0.500684  ...  3656.172367  4504.348837
std      1.110807    0.500342  ...  1560.256377  1937.211452
min      1.000000    0.000000  ...    20.000000    22.000000
25%      2.000000    0.000000  ...  2497.000000  3152.000000
50%      3.000000    1.000000  ...  3662.000000  4548.000000
75%      3.000000    1.000000  ...  4776.500000  5956.000000
max      4.000000    1.000000  ...  6946.000000  8714.000000

[8 rows x 14 columns]

In [ ]:
df_cf.describe()

A1          A2          A3  ...         A13         A14         A15
count  690.000000  690.000000  690.000000  ...  690.000000  690.000000  690.000000
mean     0.678261  148.686957   82.682609  ...   58.797101   55.143478    0.444928
std      0.467482   92.932052   58.792636  ...   46.150187   72.695049    0.497318
min      0.000000    1.000000    1.000000  ...    1.000000    1.000000    0.000000
25%      0.000000   72.000000   33.000000  ...   24.000000    1.000000    0.000000
50%      1.000000  134.500000   70.000000  ...   53.000000    6.000000    0.000000
75%      1.000000  219.750000  125.750000  ...   95.000000  107.750000    1.000000
max      1.000000  350.000000  215.000000  ...  171.000000  240.000000    1.000000

[8 rows x 15 columns]

In [ ]:
df_cs.describe()

COMPACTNESS  CIRCULARITY  ...  HOLLOWS_RATIO       Class
count   846.000000   846.000000  ...     846.000000  846.000000
mean     93.678487    44.861702  ...     195.632388    1.469267
std       8.234474     6.169866  ...       7.438797    1.111905
min      73.000000    33.000000  ...     181.000000    0.000000
25%      87.000000    40.000000  ...     190.250000    0.000000
50%      93.000000    44.000000  ...     197.000000    1.000000
75%     100.000000    49.000000  ...     201.000000    2.000000
max     119.000000    59.000000  ...     211.000000    3.000000

[8 rows x 19 columns]

Os modelos implementados no sklearn recebem como entrada para a modelagam um ou mais arrays. Dessa forma, precisamos modificar o df original para que seja possível a modelagem correta. 

Para isso, vamos separar o label das amotras, armazenar o nome das featues já que os arrays não fazem isso e depois retirar a coluna de labels do df original. Em seguida, vamos converter o df para array usando o numpy!

In [ ]:
#df regressor

# armazenando os labels em um array
labels_r = np.array(df_r['cnt'])

# salvando a ordem das features
feature_list_r = list(df_r.columns)

# removendo a coluna de labels do df original
df_r = df_r.drop('cnt', axis = 1)

# check
df_r.columns

Index(['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered'],
      dtype='object')

In [ ]:
# convertendo df para array
data_r = np.array(df_r)

In [ ]:
#df classifiers

# armazenando os labels em um array
labels_cf = np.array(df_cf['A15'])

# salvando a ordem das features
feature_list_cf = list(df_cf.columns)

# removendo a coluna de labels do df original
df_cf = df_cf.drop('A15', axis = 1)

# check
df_cf.columns

Index(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11',
       'A12', 'A13', 'A14'],
      dtype='object')

In [ ]:
# convertendo df para array
data_cf = np.array(df_cf)

In [ ]:
#df cluster _cs

# armazenando os labels em um array
labels_cs = np.array(df_cs['Class'])

# salvando a ordem das features
feature_list_cs = list(df_cs.columns)

# removendo a coluna de labels do df original
df_cs = df_cs.drop('Class', axis = 1)

# check
df_cs.columns

Index(['COMPACTNESS', 'CIRCULARITY', 'DISTANCE_CIRCULARITY', 'RADIUS_RATIO',
       'PR.AXIS_ASPECT_RATIO', 'MAX.LENGTH_ASPECT_RATIO', 'SCATTER_RATIO',
       'ELONGATEDNESS', 'PR.AXIS_RECTANGULARITY', 'MAX.LENGTH_RECTANGULARITY',
       'SCALED_VARIANCE_MAJOR', 'SCALED_VARIANCE_MINOR',
       'SCALED_RADIUS_OF_GYRATION', 'SKEWNESS_ABOUT_MAJOR',
       'SKEWNESS_ABOUT_MINOR', 'KURTOSIS_ABOUT_MAJOR', 'KURTOSIS_ABOUT_MINOR',
       'HOLLOWS_RATIO'],
      dtype='object')

In [ ]:
# convertendo df para array
data_cs = np.array(df_cs)

Agora estamos quase prontos para a modelagem em si!

Precisamos apenas separar uma parte dos nossos dados para que seja possível avaliar os modelos que vamos treinar. O sklearn tem uma função para isso: <a href = http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html> train_test_split<a>.

In [ ]:
# importar train_test_split do scikitlearn 
from sklearn.model_selection import train_test_split

# aplicando a funcao train_test_split para separar os conjuntos de treino e 
# teste segundo uma porcentagem de separação definida. 

#regressao
train_reg, test_reg, train_labels_reg, test_labels_reg = train_test_split(data_r, labels_r, test_size=0.25, random_state=42)

#classificação
train_class, test_class, train_labels_class, test_labels_class = train_test_split(data_cf, labels_cf, test_size=0.25, random_state=42)

#clustering
train_clust, test_clust, train_labels_clust, test_labels_clust = train_test_split(data_cs, labels_cs, test_size=0.25, random_state=42)

### RF Regressor

In [ ]:
# importar o modelo de regressão linear
from sklearn.ensemble import RandomForestRegressor 

# treinando o modelo no conjunto de dados de treino
regression = RandomForestRegressor().fit(train_reg, train_labels_reg);

In [ ]:
# aplicando o modelo treinado para a previsão da temperatura 
#em todo o conjunto de teste
predictions1_labels = regression.predict(test_reg)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels_reg, 'Previsto': predictions1_labels})  
p.head(10)

Real  Previsto
0  6606   6711.64
1  1550   1556.69
2  3747   3701.59
3  6041   6072.51
4  7538   7617.84
5  7264   7350.24
6  1605   1599.68
7  2209   2192.72
8  7499   7610.37
9  5743   5904.52

Agora que criamos o modelo de regressão linear e aplicamos o modelo criado ao conjunto de teste, podemos então avaliar o modelo gerado. 

In [ ]:
from sklearn import metrics
#avaliando o modelo
print('R2:', metrics.r2_score(test_labels_reg, predictions1_labels)) 
print('MSE:', metrics.mean_squared_error(test_labels_reg, predictions1_labels))  
print('RMSE:', np.sqrt(metrics.mean_squared_error(test_labels_reg, predictions1_labels))) 
print('RMSLE:', np.sqrt(metrics.mean_squared_log_error(test_labels_reg, predictions1_labels))) 
print('MAE:', metrics.mean_absolute_error(test_labels_reg, predictions1_labels))

R2: 0.9972795035329695
MSE: 10484.61393060109
RMSE: 102.39440380509616
RMSLE: 0.24281466697633494
MAE: 68.5995081967213


### Classificação com Regressão Logística

In [ ]:
#importar o modelo SVR
from sklearn.linear_model import LogisticRegression

# instanciacao e determinacao dos hiperparâmetros do SVR: tipo de kernel e epsilon
classifier = LogisticRegression(max_iter=1000)

# treinando o SVR
classifier.fit(train_class, train_labels_class)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# aplicando o modelo treinado para a previsão da temperatura 
#em todo o conjunto de teste
predictions2_labels = classifier.predict(test_class)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels_class, 'Previsto': predictions2_labels})  
p.head(10)

Real  Previsto
0     1         1
1     0         0
2     1         0
3     1         1
4     0         0
5     1         0
6     1         1
7     0         0
8     0         0
9     1         0

In [ ]:
from sklearn import metrics

print('\nAcurácia\n', metrics.accuracy_score(test_labels_class, predictions2_labels)) 
print('\nAcurácia Balanceada por classe\n', metrics.balanced_accuracy_score(test_labels_class, predictions2_labels)) 
print('\nPrecision\n', metrics.precision_score(test_labels_class, predictions2_labels)) 
print('\nRecall\n', metrics.recall_score(test_labels_class, predictions2_labels)) 
print('\nF1\n', metrics.f1_score(test_labels_class, predictions2_labels)) 

print('\nAUCROC\n', metrics.roc_auc_score(test_labels_class, predictions2_labels))


Acurácia
 0.861271676300578

Acurácia Balanceada por classe
 0.8472104219767771

Precision
 0.8387096774193549

Recall
 0.7878787878787878

F1
 0.8125

AUCROC
 0.8472104219767771


### Clustering com Kmeans

In [ ]:
# importar o modelo de KMeans
from sklearn.cluster import KMeans

clustering = KMeans(n_clusters=4, random_state=42)
 
# treinando o modelo no conjunto de dados de treino
clustering.fit(train_clust);

In [ ]:
predictions3_labels = clustering.predict(test_clust)

# Exibindo dataframe com valores 10 reais e suas respectivas previsões
p = pd.DataFrame({'Real': test_labels_clust, 'Previsto': predictions3_labels})  
p.head(10)

Real  Previsto
0     0         1
1     3         3
2     0         1
3     2         1
4     0         1
5     3         1
6     3         1
7     2         0
8     0         1
9     2         0

In [ ]:
from sklearn.metrics import cluster

#avaliando o modelo
print('Coeficiente de Silhueta\n', metrics.silhouette_score(test_clust, predictions3_labels)) 
print('\nDavies-Bouldin Score\n', metrics.davies_bouldin_score(test_clust, predictions3_labels)) 

print('\nMatriz de Contingência\n', metrics.cluster.contingency_matrix(test_labels_clust, predictions3_labels)) 
print('\nMutual Information\n', metrics.mutual_info_score(test_labels_clust, predictions3_labels)) 

Coeficiente de Silhueta
 0.4459607933191861

Davies-Bouldin Score
 0.7335177712258693

Matriz de Contingência
 [[17 41  7  0]
 [14  4 15  6]
 [22 18 10  9]
 [ 0 19  0 30]]

Mutual Information
 0.30587264802533265
